// <auto-generated />
using CartoonApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartoonApi.Migrations
{
    [DbContext(typeof(CartoonContext))]
    partial class CartoonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("CartoonApi.Models.Cartoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ageRestriction")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cartoons");
                });
#pragma warning restore 612, 618
        }
    }
}
